kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-elyra-work
  labels:
    app: elyra-ai
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-elyra-runtimes
  labels:
    app: elyra-ai
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
